events {
    worker_connections 1024;
}

http {
    upstream api_backend {
        least_conn;
        server api1:8000;
        server api2:8000;
    }

    server {
        listen 80;

        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection '1; mode=block' always;

        # Frontend statique
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # API de prédiction
        location /predict {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'Content-Type';
        }

        location /health {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            add_header Access-Control-Allow-Origin *;
        }

        location /metrics {
            proxy_pass http://api_backend;
            allow 172.0.0.0/8;
            deny all;
        }
    }
}
